In [27]:
import os
Dir = r"C:\Users\Rishabh\Downloads\Inputtesting"

In [28]:
print(os.listdir(Dir))

['madebyme.nii.gz', 'vs_gk.npy', 'vs_gk_0000.nii.gz']


In [21]:
example = "C:/example_input_images/ceT1+T2"
example = "C:/example_input_images/T2"
print(os.listdir(example))

['vs_gk_t2_0000.nii.gz']


In [29]:
import nibabel as nib
import numpy as np

# Load the .nii.gz file
file_path = os.path.join(Dir, 'madebyme.nii.gz')
img = nib.load(file_path)

# Get the data as a NumPy array
data = img.get_fdata()

# Print shape and type of the data
print(f"Data shape: {data.shape}")
print(f"Data type: {data.dtype}")

# Print metadata
print("Affine matrix:")
print(img.affine)
print("\nHeader information:")
print(img.header)

# Example: Access a specific slice (e.g., slice 50)
slice_data = data[:, :, 10]

Data shape: (448, 512, 18)
Data type: float64
Affine matrix:
[[-4.10105765e-01  8.41348588e-11 -3.45179737e-02  9.09461975e+01]
 [-4.74736862e-06  4.10156131e-01  1.62281713e-03 -6.36871681e+01]
 [-6.43534493e-03 -3.02578468e-04  2.19972849e+00 -4.28403511e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

Header information:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : np.bytes_(b'')
db_name         : np.bytes_(b'')
extents         : 0
session_error   : 0
regular         : np.bytes_(b'')
dim_info        : 0
dim             : [  3 448 512  18   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : uint16
bitpix          : 16
slice_start     : 0
pixdim          : [-1.          0.41015625  0.41015625  2.2         1.          1.
  1.          1.        ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_cod

In [30]:
import nibabel as nib
import numpy as np

# Load the .nii.gz file
file_path = os.path.join(Dir, 'vs_gk_0000.nii.gz')
img = nib.load(file_path)

# Get the data as a NumPy array
data = img.get_fdata()

# Print shape and type of the data
print(f"Data shape: {data.shape}")
print(f"Data type: {data.dtype}")

# Print metadata
print("Affine matrix:")
print(img.affine)
print("\nHeader information:")
print(img.header)

# Example: Access a specific slice (e.g., slice 50)
slice_data = data[:, :, 10]

Data shape: (416, 488, 81)
Data type: float64
Affine matrix:
[[ -0.41015625   0.           0.          83.76821899]
 [  0.          -0.41015625   0.         118.152565  ]
 [  0.           0.           1.5        -78.50067139]
 [  0.           0.           0.           1.        ]]

Header information:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : np.bytes_(b'')
db_name         : np.bytes_(b'')
extents         : 0
session_error   : 0
regular         : np.bytes_(b'r')
dim_info        : 0
dim             : [  3 416 488  81   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : uint16
bitpix          : 16
slice_start     : 0
pixdim          : [1.         0.41015625 0.41015625 1.5        1.         1.
 1.         1.        ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 2
cal_max         : 

In [10]:
import nibabel as nib
import numpy as np
from scipy.ndimage import zoom

# Load the first NIfTI file
file1_path = os.path.join(Dir, 'madebyme.nii.gz')  # Update with your file path
file2_path = os.path.join(Dir, 'vs_gk_0000.nii.gz')  # Update with your file path

file1 = nib.load(file1_path)
file2 = nib.load(file2_path)

# Get the data and affine matrix from the first file
data1 = file1.get_fdata()
affine1 = file1.affine

# Get voxel sizes from the first and second files
pixdim1 = file1.header.get_zooms()  # Voxel size of the first file
pixdim2 = file2.header.get_zooms()  # Voxel size of the second file

# Resample data to match the second file's voxel size (1.5mm in Z dimension)
zoom_factors = np.array(pixdim1[:3]) / np.array(pixdim2[:3])
resampled_data = zoom(data1, zoom_factors, order=1)  # Interpolation order = 1 (linear interpolation)

# Adjust the affine matrix of the first file to match the second file
affine2 = file2.affine

# Save the new resampled file with the adjusted affine matrix
new_img = nib.Nifti1Image(resampled_data, affine2)
new_img.to_filename('converted_file.nii.gz')  # Save the output file

print("Conversion completed! The new file is saved as 'converted_file.nii.gz'.")


FileNotFoundError: No such file or no access: 'path_to_first_file.nii.gz'

In [11]:
import nibabel as nib
import numpy as np

# Load the first NIfTI file
file1_path = os.path.join(Dir, 'madebyme.nii.gz')  # Update with your file path
file2_path = os.path.join(Dir, 'vs_gk_0000.nii.gz')  # Update with your file path

file1 = nib.load(file1_path)
file2 = nib.load(file2_path)

# Get data and affine matrices
data1 = file1.get_fdata()
affine1 = file1.affine

# Get voxel sizes and affine from the second file
pixdim2 = file2.header.get_zooms()  # Voxel size of the second file
affine2 = file2.affine  # Affine of the second file

# Calculate the scaling factor for the slice thickness
scale_z = pixdim2[2] / file1.header.get_zooms()[2]

# Adjust the affine matrix for slice thickness (Z-dimension)
new_affine = affine1.copy()
new_affine[2, 2] = affine1[2, 2] * scale_z  # Adjust Z scaling

# Keep the number of slices the same, but change the slice thickness in the affine matrix
new_img = nib.Nifti1Image(data1, new_affine)

# Save the new image with the adjusted affine matrix (same data, new spacing)
new_img.to_filename('converted_file.nii.gz')  # Save the output file

print("Conversion completed! The new file is saved as 'converted_file.nii.gz'.")


Conversion completed! The new file is saved as 'converted_file.nii.gz'.


In [16]:
import numpy as np

# Specify the path to your .npy file
file_path = os.path.join(Dir,'vs_gk.npy')  # Update with your file path

# Load the .npy file
data = np.load(file_path)

# Print the data to inspect
print(data.shape)


(2, 26, 422, 444)


In [25]:
import nibabel as nib
import numpy as np
import os

# Load the .nii.gz file
file_path = os.path.join(example, 'vs_gk_t2_0000.nii.gz')
img = nib.load(file_path)

# Get the data as a NumPy array
data = img.get_fdata()

# Access the first 10 slices (slices 0 to 9)
slices_data = data[:, :, :10]

# Create a new NIfTI image with the first 10 slices
new_img = nib.Nifti1Image(slices_data, img.affine)

# Save the new image to a file
output_path = os.path.join(example, 'first_10_slices.nii.gz')
nib.save(new_img, output_path)

print(f"Saved new file at: {output_path}")



Saved new file at: C:/example_input_images/T2\first_10_slices.nii.gz
